parent_cfg: 'configs/enerf/enerf_outdoor/actor1.yaml'
visualizer_module: lib.visualizers.enerf_interactive
train_dataset_module: lib.datasets.enerf_outdoor.enerf_interactive
test_dataset_module: lib.datasets.enerf_outdoor.enerf_interactive

test_dataset:
    frames: [0, 1000, 250] # Render frames
    input_ratio: 0.5